### ISSUE TITLE
cannot be cast to javax.management.remote.JMXConnector

### ISSUE THREAD

**Issue by 954L** [smartloli/EFAK#569]
at org.smartloli.kafka.eagle.web.quartz.MBeanSubTask$KafkaClusterSubThread.run(MBeanSubTask.java:104)
[2021-11-17 14:03:00] KafkaServiceImpl.Thread-69 - ERROR - Get kafka os memory from jmx has error, msg is java.io.IOException cannot be cast to javax.management.remote.JMXConnector
 [2021-11-17 14:03:00] KafkaServiceImpl.Thread-69 - ERROR - Get kafka os memory from jmx has error, msg is java.io.IOException cannot be cast to javax.management.remote.JMXConnector
 [2021-11-17 14:03:00] KafkaServiceImpl.Thread-69 - ERROR - Get kafka broker used cpu value has error, msg is
 java.lang.ClassCastException: java.io.IOException cannot be cast to javax.management.remote.JMXConnector
        at org.smartloli.kafka.eagle.common.util.JMXFactoryUtils.connectWithTimeout(JMXFactoryUtils.java:103)
        at org.smartloli.kafka.eagle.core.factory.KafkaServiceImpl.getUsedCpuValue(KafkaServiceImpl.java:1706)
        at org.smartloli.kafka.eagle.web.quartz.MBeanSubTask$KafkaClusterSubThread.kafkaAssembly(MBeanSubTask.java:214)
        at org.smartloli.kafka.eagle.web.quartz.MBeanSubTask$KafkaClusterSubThread.kafkaCluster(MBeanSubTask.java:121)
        at org.smartloli.kafka.eagle.web.quartz.MBeanSubTask$KafkaClusterSubThread.run(MBeanSubTask.java:104)

![image](https://user-images.githubusercontent.com/35250721/142149837-56c246c0-b1a7-4062-a71c-5213e9c2f5a0.png)
![image](https://user-images.githubusercontent.com/35250721/142149932-3f502120-5bde-4523-bce4-764f7733da7d.png)

**Comment by xingkongtc** [comment]
https://www.cxyzjd.com/article/u013568834/108086266
