### ISSUE TITLE
 ERROR - Read ZK buffer has error  dashboard监控的内容为空

### ISSUE THREAD

**Issue by yunfeng79** [smartloli/EFAK#573]
eagle 2.0.8
[2021-12-10 09:23:00] ZKMetricsUtils.Thread-28453 - ERROR - Read ZK buffer has error,msg is 断开的管道 (Write failed)
 [2021-12-10 09:23:05] KafkaZKPoolUtils.Thread-21881 - ERROR - Error initializing zookeeper, msg is 
 kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
        at kafka.zookeeper.ZooKeeperClient.$anonfun$waitUntilConnected$3(ZooKeeperClient.scala:230)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:251)
        at kafka.zookeeper.ZooKeeperClient.waitUntilConnected(ZooKeeperClient.scala:226)
        at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:95)
        at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1581)
        at kafka.zk.KafkaZkClient.apply(KafkaZkClient.scala)
        at org.smartloli.kafka.eagle.common.util.KafkaZKPoolUtils.getZkClient(KafkaZKPoolUtils.java:122)
        at org.smartloli.kafka.eagle.core.factory.v2.BrokerServiceImpl.topicList(BrokerServiceImpl.java:371)
        at org.smartloli.kafka.eagle.web.quartz.TopicRankSubTask$LogsizeStatsSubThread.topicLogsizeStats(TopicRankSubTask.java:276)
        at org.smartloli.kafka.eagle.web.quartz.TopicRankSubTask$LogsizeStatsSubThread.run(TopicRankSubTask.java:259)
[2021-12-10 09:23:05] KafkaZKPoolUtils.Thread-21881 - ERROR - Kafka cluster[cluster1.zk.list] address has null.
 [2021-12-10 09:23:05] BrokerServiceImpl.Thread-21881 - ERROR - Get topic list has error, msg is 

dashboard监控的内容为空。

**Comment by JacobAP** [comment]
> [2021-12-10 09:23:05] KafkaZKPoolUtils.Thread-21881 - ERROR - Kafka cluster[cluster1.zk.list] address has null.

根据这行日志，应该是配置文件system-config.properties中的 cluster1.zk.list 配置有问题，可以加微信 golden_arch交流下

**Comment by JacobAP** [comment]
还有，kafka的JMX端口未打开的话也会导致这个问题

**Comment by yunfeng79** [comment]
@JacobAP  kafka的JMX 端口打开了，我检查了下cluster1.zk.list 是写的zookeeper集群地址端口

**Comment by yunfeng79** [comment]
2.0.9版本还是有报错：[2021-12-14 10:41:40] KafkaZKPoolUtils.Thread-12693 - ERROR - Error initializing zookeeper, msg is 
 kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
        at kafka.zookeeper.ZooKeeperClient.$anonfun$waitUntilConnected$3(ZooKeeperClient.scala:230)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:251)
        at kafka.zookeeper.ZooKeeperClient.waitUntilConnected(ZooKeeperClient.scala:226)
        at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:95)
        at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1581)
        at kafka.zk.KafkaZkClient.apply(KafkaZkClient.scala)
        at org.smartloli.kafka.eagle.common.util.KafkaZKPoolUtils.getZkClient(KafkaZKPoolUtils.java:135)
        at org.smartloli.kafka.eagle.core.factory.v2.BrokerServiceImpl.topicMetadata(BrokerServiceImpl.java:503)
        at org.smartloli.kafka.eagle.core.factory.v2.BrokerServiceImpl.getBrokerSpreadByTopic(BrokerServiceImpl.java:225)
        at org.smartloli.kafka.eagle.web.quartz.shard.task.sub.PerformanceByTopicStatsSubTask.brokerPerformanceByTopicStats(PerformanceByTopicStatsSubTask.java:79)
        at org.smartloli.kafka.eagle.web.quartz.shard.task.sub.PerformanceByTopicStatsSubTask.run(PerformanceByTopicStatsSubTask.java:53)
[2021-12-14 10:41:40] KafkaZKPoolUtils.Thread-12693 - ERROR - Kafka cluster[cluster1.zk.list] address has null.
 [2021-12-14 10:41:40] BrokerServiceImpl.Thread-12693 - ERROR - Get topic metadata records has error, msg is 
 java.lang.NullPointerException
[2021-12-14 10:42:00] ZKMetricsUtils.Thread-13469 - ERROR - Read ZK buffer has error,msg is 断开的管道 (Write failed)
 [2021-12-14 10:42:00] ZKMetricsUtils.Thread-13469 - ERROR - Read ZK buffer has error,msg is 断开的管道 (Write failed)
 [2021-12-14 10:42:11] KafkaZKPoolUtils.Thread-12695 - ERROR - Error initializing zookeeper, msg is 
 kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
        at kafka.zookeeper.ZooKeeperClient.$anonfun$waitUntilConnected$3(ZooKeeperClient.scala:230)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:251)
        at kafka.zookeeper.ZooKeeperClient.waitUntilConnected(ZooKeeperClient.scala:226)
        at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:95)
        at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1581)
        at kafka.zk.KafkaZkClient.apply(KafkaZkClient.scala)
        at org.smartloli.kafka.eagle.common.util.KafkaZKPoolUtils.getZkClient(KafkaZKPoolUtils.java:135)
        at org.smartloli.kafka.eagle.core.factory.KafkaServiceImpl.getAllBrokersInfo(KafkaServiceImpl.java:221)
        at org.smartloli.kafka.eagle.web.quartz.shard.task.sub.TopicThroughputByteInTask.throughput(TopicThroughputByteInTask.java:86)
        at org.smartloli.kafka.eagle.web.quartz.shard.task.sub.TopicThroughputByteInTask.run(TopicThroughputByteInTask.java:67)
[2021-12-14 10:42:11] KafkaZKPoolUtils.Thread-12695 - ERROR - Kafka cluster[cluster1.zk.list] address has null.
 [2021-12-14 10:42:11] KafkaServiceImpl.Thread-12695 - ERROR - Get all brokers info has error,msg is 
 java.lang.NullPointerException
