### ISSUE TITLE
topic 显示一直在加载

### ISSUE THREAD

**Issue by yunfeng79** [smartloli/EFAK#576]
![image](https://user-images.githubusercontent.com/21050635/145926372-bdd62cc2-f05e-49d6-be0f-280b70e483c1.png)
 [2021-12-14 11:12:45] KafkaServiceImpl.Thread-12600 - ERROR - Find topic partition has error, msg is 
 java.lang.NullPointerException
        at org.smartloli.kafka.eagle.core.factory.KafkaServiceImpl.findTopicPartition(KafkaServiceImpl.java:136)
        at org.smartloli.kafka.eagle.web.quartz.shard.task.sub.MetricsConsumerSubTask.bscreenConsumerTopicStats(MetricsConsumerSubTask.java:167)
        at org.smartloli.kafka.eagle.web.quartz.shard.task.sub.MetricsConsumerSubTask.metricsConsumerTopicQuartz(MetricsConsumerSubTask.java:73)
        at org.smartloli.kafka.eagle.web.quartz.shard.task.sub.MetricsConsumerSubTask.run(MetricsConsumerSubTask.java:68)
[2021-12-14 11:12:45] MetricsConsumerSubTask.Thread-12600 - ERROR - Collector consumer topic data has error, msg is 
 java.lang.NullPointerException
        at org.smartloli.kafka.eagle.web.quartz.shard.task.sub.MetricsConsumerSubTask.bscreenConsumerTopicStats(MetricsConsumerSubTask.java:169)
        at org.smartloli.kafka.eagle.web.quartz.shard.task.sub.MetricsConsumerSubTask.metricsConsumerTopicQuartz(MetricsConsumerSubTask.java:73)
        at org.smartloli.kafka.eagle.web.quartz.shard.task.sub.MetricsConsumerSubTask.run(MetricsConsumerSubTask.java:68)

**Comment by aurorazl** [comment]
zookeeper地址确认有没有问题

**Comment by sys122** [comment]
同问这个问题，zk地址确认没有问题
