### ISSUE TITLE
点动broker后台报错

### ISSUE THREAD

**Issue by yunfeng79** [smartloli/EFAK#577]
![image](https://user-images.githubusercontent.com/21050635/146145269-0df09e4b-06e3-45f4-927f-31f5ef679c64.png)
点动broker 页面反应慢
后台报错
Caused by: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 180000, active 100, maxActive 100, creating 0, runningSqlCount 98 : select logsize,offsets,timespan from ke_consumer_bscreen
                where `cluster`=? and `group`=?
                and `topic`=? order by `timespan` desc limit 2
runningSqlCount 2 : select `cluster`,`group`,`topic`,`logsize`,`difflogsize`,`offsets`,`diffoffsets`,`lag` from ke_consumer_bscreen
        where `cluster` =? and
        `group`=? and
        `topic`=?
        order by `timespan` desc limit 1
        at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1276)
        at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1095)
        at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4544)
        at com.alibaba.druid.filter.stat.StatFilter.dataSource_getConnection(StatFilter.java:670)
        at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4540)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1073)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1065)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:104)
        at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158)
        at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116)
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79)
        ... 25 more

**Comment by aurorazl** [comment]
你配置的mysql？mysql服务本身状态正常吗
