### ISSUE TITLE
2.08版本获取不到kafka，zk，版本信息，jmx端口是开着的

### ISSUE THREAD

**Issue by liquan00759** [smartloli/EFAK#578]
[2021-12-15 17:19:01] Mx4jServiceImpl.Thread-310 - ERROR - JMX service url[10.255.50.54:9999] create has error,msg is
 [2021-12-15 17:19:01] Mx4jServiceImpl.Thread-310 - ERROR - JMX service url[10.255.50.55:9999] create has error,msg is
 java.lang.ClassCastException: java.rmi.ConnectException cannot be cast to javax.management.remote.JMXConnector
        at org.smartloli.kafka.eagle.common.util.JMXFactoryUtils.connectWithTimeout(JMXFactoryUtils.java:103)
        at org.smartloli.kafka.eagle.core.factory.Mx4jServiceImpl.common(Mx4jServiceImpl.java:231)
        at org.smartloli.kafka.eagle.core.factory.Mx4jServiceImpl.bytesOutPerSec(Mx4jServiceImpl.java:79)
        at org.smartloli.kafka.eagle.web.quartz.TopicRankSubTask$TopicThroughputThread.throughputByteOut(TopicRankSubTask.java:221)
        at org.smartloli.kafka.eagle.web.quartz.TopicRankSubTask$TopicThroughputThread.throughput(TopicRankSubTask.java:111)
        at org.smartloli.kafka.eagle.web.quartz.TopicRankSubTask$TopicThroughputThread.run(TopicRankSubTask.java:103)
[2021-12-15 17:19:01] Mx4jServiceImpl.Thread-303 - ERROR - Get topic size from jmx has error, msg is java.rmi.ConnectException cannot be cast to javax.management.remote.JMXConnector
 [2021-12-15 17:19:02] Mx4jServiceImpl.Thread-310 - ERROR - JMX service url[10.255.50.53:9999] create has error,msg is
 java.lang.ClassCastException: java.rmi.ConnectException cannot be cast to javax.management.remote.JMXConnector
        at org.smartloli.kafka.eagle.common.util.JMXFactoryUtils.connectWithTimeout(JMXFactoryUtils.java:103)
        at org.smartloli.kafka.eagle.core.factory.Mx4jServiceImpl.common(Mx4jServiceImpl.java:231)
        at org.smartloli.kafka.eagle.core.factory.Mx4jServiceImpl.bytesOutPerSec(Mx4jServiceImpl.java:79)
        at org.smartloli.kafka.eagle.web.quartz.TopicRankSubTask$TopicThroughputThread.throughputByteOut(TopicRankSubTask.java:221)
        at org.smartloli.kafka.eagle.web.quartz.TopicRankSubTask$TopicThroughputThread.throughput(TopicRankSubTask.java:111)
        at org.smartloli.kafka.eagle.web.quartz.TopicRankSubTask$TopicThroughputThread.run(TopicRankSubTask.java:103)
[2021-12-15 17:19:02] Mx4jServiceImpl.Thread-303 - ERROR - Get topic size from jmx has error, msg is java.rmi.ConnectException cannot be cast to javax.management.remote.JMXConnector
 [2021-12-15 17:19:02] Mx4jServiceImpl.Thread-303 - ERROR - Get topic size from jmx has error, msg is java.rmi.ConnectException cannot be cast to javax.management.remote.JMXConnector
 [2021-12-15 17:19:02] Mx4jServiceImpl.Thread-303 - ERROR - Get topic size from jmx has error, msg is java.rmi.ConnectException cannot be cast to javax.management.remote.JMXConnector

**Comment by liquan00759** [comment]
[2021-12-15 18:16:01] Mx4jServiceImpl.Thread-1044 - ERROR - Get topic size from jmx has error, msg is null
 [2021-12-15 18:16:01] Mx4jServiceImpl.Thread-1044 - ERROR - Get topic size from jmx has error, msg is null
 [2021-12-15 18:16:01] Mx4jServiceImpl.Thread-1044 - ERROR - Get topic size from jmx has error, msg is null

**Comment by MrGlory** [comment]
原因如下：https://blog.csdn.net/zhaofuqiangmycomm/article/details/88535690
在kafka-server-start.sh中开放jmx端口处增加-Djava.rmi.server.hostname参数可解决
```
 export KAFKA_HEAP_OPTS="-Xms2G -Xmx2G -Djava.rmi.server.hostname=域名\ip"
 export JMX_PORT="9999"
```

**Comment by hyhyf** [comment]
> 原因如下：https://blog.csdn.net/zhaofuqiangmycomm/article/details/88535690 在kafka-server-start.sh中开放jmx端口处增加-Djava.rmi.server.hostname参数可解决
> 
> ```
>  export KAFKA_HEAP_OPTS="-Xms2G -Xmx2G -Djava.rmi.server.hostname=域名\ip"
>  export JMX_PORT="9999"
> ```

thanks a lot!
