### ISSUE TITLE
EMAIL alarm setting URL parting problem

### ISSUE THREAD

**Issue by fzhougithub** [smartloli/EFAK#594]
When type in EMAIl URL like

http://127.0.0.1:10086/email

Got the error like below, looks like it is casting error.  The EFAK is 2.10. Does it require certain version of JAVA? We are using oracle jdk1.8.0_172. 

Thanks

 
[2022-03-09 14:55:10] JSONUtils.DefaultQuartzScheduler_Worker-10 - ERROR - Verify that the string[http://127.0.0.1:10086/email] is JSONObject has error, msg is
 com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2http://127.0.0.1:10086/email
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1507)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1393)
	at com.alibaba.fastjson.JSON.parse(JSON.java:181)
	at com.alibaba.fastjson.JSON.parse(JSON.java:191)
	at com.alibaba.fastjson.JSON.parse(JSON.java:147)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:252)
	at org.smartloli.kafka.eagle.common.util.JSONUtils.isJsonObject(JSONUtils.java:36)
	at org.smartloli.kafka.eagle.api.im.queue.MailJob.sendMsg(MailJob.java:54)
	at org.smartloli.kafka.eagle.api.im.queue.MailJob.execute(MailJob.java:50)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
[2022-03-09 14:55:10] HttpClientUtils.DefaultQuartzScheduler_Worker-10 - ERROR - Do post form request has error, msg is
 org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:10086 [/127.0.0.1] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.smartloli.kafka.eagle.common.util.HttpClientUtils.doPostForm(HttpClientUtils.java:96)
	at org.smartloli.kafka.eagle.api.im.queue.MailJob.sendMsg(MailJob.java:67)
	at org.smartloli.kafka.eagle.api.im.queue.MailJob.execute(MailJob.java:50)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 14 more

**Comment by fzhougithub** [comment]
Any update on this issue? Thanks
